service: bd-2020-1-trabalho-final


# Cloud provider settings
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    DB_HOST: ${file(credentials.yml):DB_HOST}
    DB_NAME: ${file(credentials.yml):DB_NAME} 
    DB_USER: ${file(credentials.yml):DB_USER} 
    DB_PASSWORD: ${file(credentials.yml):DB_PASSWORD} 



# Define functions here
functions:
  atendimentos:
    handler: src/functions/database/atendimentos.handler
    events:
      - http:
          method: get
          path: api/atendimentos
          cors: true
  clinicas:
    handler: src/functions/database/clinicas.handler
    events:
      - http:
          method: get
          path: api/clinicas
          cors: true
  desfechos:
    handler: src/functions/database/desfechos.handler
    events:
      - http:
          method: get
          path: api/desfechos
          cors: true
  enderecos:
    handler: src/functions/database/enderecos.handler
    events:
      - http:
          method: get
          path: api/enderecos
          cors: true
  estados:
    handler: src/functions/database/estados.handler
    events:
      - http:
          method: get
          path: api/estados
          cors: true
  exames:
    handler: src/functions/database/exames.handler
    events:
      - http:
          method: get
          path: api/exames
          cors: true
  locais_de_exame:
    handler: src/functions/database/locais_de_exame.handler
    events:
      - http:
          method: get
          path: api/locais-de-exame
          cors: true
  municipios:
    handler: src/functions/database/municipios.handler
    events:
      - http:
          method: get
          path: api/municipios
          cors: true
  pacientes:
    handler: src/functions/database/pacientes.handler
    events:
      - http:
          method: get
          path: api/pacientes
          cors: true
  paises:
    handler: src/functions/database/paises.handler
    events:
      - http:
          method: get
          path: api/paises
          cors: true
  sexos:
    handler: src/functions/database/sexos.handler
    events:
      - http:
          method: get
          path: api/sexos
          cors: true
  tipos_de_atendimento:
    handler: src/functions/database/tipos_de_atendimento.handler
    events:
      - http:
          method: get
          path: api/tipos-de-atendimento
          cors: true
  tipos_de_desfecho:
    handler: src/functions/database/tipos_de_desfecho.handler
    events:
      - http:
          method: get
          path: api/tipos-de-desfecho
          cors: true
  tipos_de_exame:
    handler: src/functions/database/tipos_de_exame.handler
    events:
      - http:
          method: get
          path: api/tipos-de-exame
          cors: true
  unidades:
    handler: src/functions/database/unidades.handler
    events:
      - http:
          method: get
          path: api/unidades
          cors: true
  analitos:
    handler: src/functions/database/analitos.handler
    events:
      - http:
          method: get
          path: api/analitos
          cors: true
  desfechos-resumo:
    handler: src/functions/desfechos_resumo.handler
    events:
      - http:
          method: get
          path: api/desfechos-resumo
          cors: true
  altas-administrativas:
    handler: src/functions/altas_administrativas.handler
    events:
      - http:
          method: get
          path: api/altas-administrativas
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux